### PR TITLE
Run automatic fix for open advisories

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
`npm audit fix` run on top of commit b919d1d, solves:

* https://www.npmjs.com/advisories/755
* https://www.npmjs.com/advisories/788
* https://www.npmjs.com/advisories/813

The following advisory remains unaddressed:

* https://www.npmjs.com/advisories/745

---

### Further details

We're trying to get rid of open advisories as advertised by `npm audit` in https://github.com/digital-asset/daml-js, some of which lead to this project. The expected security risk is very low, but we'd still like to get the low hanging fruits.

I haven't been able to run `npm test` to verify I didn't introduce any regression, is there something I'm missing on how to run tests on this project?

I'd like to take advantage of this situation to **thank you** for the work you have done on this project. I hope I can contribute something more substantial to it in the future. :slightly_smiling_face:

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
FYI I just opened a PR on `remarkable` (https://github.com/jonschlinkert/remarkable/pull/337) to get rid of the remaining advisory.

**Comment by jedrivisser** [comment]
Thanks you, I just came here open a ticket for this

**Comment by agreatfool** [comment]
Thank u for the pr, I will merge it asap

**Comment by agreatfool** [comment]
Done, version 2.5.3 has been released.

**Comment by stefanobaghino-da** [comment]
Thanks for the very quick response time!

**Pull request merged**
