### PR TITLE
Return message from setters for chaining

### PR DESCRIPTION
**Pull request by rhinodavid**
I've noticed a discrepancy between the `jspb` implementation and the type definitions. All the field setters in `jspb` [return the message](https://github.com/protocolbuffers/protobuf/blob/743a4322ba8332d0b78e30a699e1f3538f8b2093/js/message.js#L982) so that you can chain setters, but the package generates setters with a return type `void`.

A test case:

```
// test.proto
syntax = "proto3";

package test;

message GetBalanceRequest {
    string address = 1;
}
```

Without changes:
```
// package: test
// file: test.proto

/* tslint:disable */
/* eslint-disable */

import * as jspb from "google-protobuf";

export class Test extends jspb.Message { 
    getAString(): string;
    setAString(value: string): void;

    clearRepeatedStringsList(): void;
    getRepeatedStringsList(): Array<string>;
    setRepeatedStringsList(value: Array<string>): void;
    addRepeatedStrings(value: string, index?: number): string;


    serializeBinary(): Uint8Array;
    toObject(includeInstance?: boolean): Test.AsObject;
    static toObject(includeInstance: boolean, msg: Test): Test.AsObject;
    static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
    static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
    static serializeBinaryToWriter(message: Test, writer: jspb.BinaryWriter): void;
    static deserializeBinary(bytes: Uint8Array): Test;
    static deserializeBinaryFromReader(message: Test, reader: jspb.BinaryReader): Test;
}


```

With changes:
```
// package: test
// file: test.proto

/* tslint:disable */
/* eslint-disable */

import * as jspb from "google-protobuf";

export class Test extends jspb.Message { 
    getAString(): string;
    setAString(value: string): Test;

    clearRepeatedStringsList(): void;
    getRepeatedStringsList(): Array<string>;
    setRepeatedStringsList(value: Array<string>): Test;
    addRepeatedStrings(value: string, index?: number): Test;


    serializeBinary(): Uint8Array;
    toObject(includeInstance?: boolean): Test.AsObject;
    static toObject(includeInstance: boolean, msg: Test): Test.AsObject;
    static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
    static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
    static serializeBinaryToWriter(message: Test, writer: jspb.BinaryWriter): void;
    static deserializeBinary(bytes: Uint8Array): Test;
    static deserializeBinaryFromReader(message: Test, reader: jspb.BinaryReader): Test;
}

export namespace Test {
    export type AsObject = {
        aString: string,
        repeatedStringsList: Array<string>,
    }
}

```

### CODE REVIEW

**Comment by rhinodavid** [comment]
Did some more digging on this. The `protobuf` package does indeed output setters which return the message and can be chained, but unfortunately the dependency version in `grpc-tools` hasn't been bumped since September '18. I opened [a pr](https://github.com/grpc/grpc-node/pull/1370) to bump it, so once this PR should be good to go.

**Comment by agreatfool** [comment]
That's cool. Thank you very much.

**Comment by rhinodavid** [comment]
https://github.com/grpc/grpc-node/releases/tag/grpc-tools%401.9.0 has been released and this should be good to go

**Comment by agreatfool** [comment]
New version 4.0.0 has been released. Thanks.

**Comment by RMHonor** [comment]
Chaining still doesn't work after setting a field, it looks like we need to upgrade to a later version of `google-protobuf`, as the version here doesn't return the message: https://github.com/protocolbuffers/protobuf/blob/97dd175a917fcdf1a0e0421659498a974f3a464a/js/message.js#L882

**Comment by agreatfool** [comment]
@RMHonor Yeah, you are right. 

Codes in the example dir cannot work properly since the version of lib `google-protobuf` is too old. Since codes run with generated js are all belongs to this lib.

And there are no changes necessary for `grpc_tools_node_protoc_ts`, I would update the package.json file in example later.

截屏2020-07-31 下午11 45 32

截屏2020-07-31 下午11 45 48

截屏2020-07-31 下午11 46 11

**Pull request merged**
