### PR TITLE
Fix generating nested enums in proto files with no package

### PR DESCRIPTION
**Pull request by bbqsrc**
if you have a proto that looks like the following:

```
syntax = "proto3";

message Foo {
  enum Bar {
    A = 1;
    B = 2;
  }
  Bar bar = 1;
}
```

It will fail to build. This is because the `enumMap` is adding `Foo.Bar` as `.Foo.Bar`. This patch fixes that.

### CODE REVIEW

**Comment by agreatfool** [comment]
Hello,

Thank u for ur PR. 

I just test your issue with actions below, and the building succeeded without any error. Could you please show me your versions:

* node --version
* npm --version
* protoc --version
* grpc_tools_node_protoc --version
* npm list -g --depth=0 | grep grpc-tools

My test steps:

* Edit code `examples/proto/book.proto`, add your test message described in your description
* Run bash `examples/bash/build.sh`
* See result

As my result, new definition generated like below:

```typescript
export class Foo extends jspb.Message { 
    getBar(): Foo.Bar;
    setBar(value: Foo.Bar): void;


    serializeBinary(): Uint8Array;
    toObject(includeInstance?: boolean): Foo.AsObject;
    static toObject(includeInstance: boolean, msg: Foo): Foo.AsObject;
    static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
    static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
    static serializeBinaryToWriter(message: Foo, writer: jspb.BinaryWriter): void;
    static deserializeBinary(bytes: Uint8Array): Foo;
    static deserializeBinaryFromReader(message: Foo, reader: jspb.BinaryReader): Foo;
}

export namespace Foo {
    export type AsObject = {
        bar: Foo.Bar,
    }

    export enum Bar {
    A = 0,
    B = 1,
    }

}
```

**Comment by bbqsrc** [comment]
The commit is small enough that you can see it is a simple logic error. If the scope is a blank string, it will be prefixed with a `.` regardless because the variable that was created explicitly to work around that case was not reused in the correct number of positions.

```$     node --version
v10.8.0
$     npm --version
6.4.0
$     protoc --version
libprotoc 3.6.0
$     grpc_tools_node_protoc --version
libprotoc 3.4.0
$     npm list -g --depth=0 | grep grpc-tools
├── grpc-tools@1.6.6```

**Comment by agreatfool** [comment]
I just tested again, and got the idea.

The reason why simple test code you provided failed is that code has `no package` defined. And previously I just appended the test code in example code, and it has package already defined, so no error encountered.

Critical issue code is here: https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/c2a4470ae700bd90a821bdc5731a81aa47048f8d/src/lib/ExportMap.ts#L60

I will merge it asap.

**Comment by agreatfool** [comment]
Just merged & new version 2.3.2 has been published. Thank you for your PR.

**Pull request merged**
